import "../../(shop)/globals.css";

import { type ReactNode } from "react";

import { AdminHeader, AdminSidebar } from "@/layout";
import { AdminMainWrapper, Toast } from "@/components";
import { getServerSession } from "@/libs";
import ForbbidenPage from "./forbidden";

export const metadata = {
  title: "Panel de administración",
  description: "Generated by Next.js",
};

interface AdminLayoutProps {
  children: ReactNode;
}

export default async function AdminLayout({ children }: AdminLayoutProps) {
  const session = await getServerSession();
  const sessionUser = session?.session;
  const user = session?.user;

  return (
    <html lang="es">
      <head></head>
      <body 
        className="font-body bg-[#F2F7FB] antialiased"
        suppressHydrationWarning
      >
        {user && sessionUser ? (
          <>
            <AdminHeader />
            <AdminSidebar />
            <AdminMainWrapper>
              {children}
            </AdminMainWrapper>
            <Toast />
          </>
        ) : (
          <ForbbidenPage />
        )}
      </body>
    </html>
  );
}
