import "../../(shop)/globals.css";

import { type ReactNode } from "react";

import { AdminHeader, AdminSidebar } from "@/layout";
import { AdminMainWrapper, Toast } from "@/components";

export const metadata = {
  title: "Panel de administración",
  description: "Generated by Next.js",
};

interface AdminLayoutProps {
  children: ReactNode;
}

export default async function AdminLayout({ children }: AdminLayoutProps) {
  return (
    <html lang="en">
      <head></head>
      <body 
        className="font-body bg-[#F2F7FB] antialiased"
        suppressHydrationWarning
      >
        <AdminHeader />
        <AdminSidebar />
        <AdminMainWrapper>
          {children}
        </AdminMainWrapper>
        <Toast />
      </body>
    </html>
  );
}
