import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Header, NavigationMenu, Footer } from "@/layout";
import { Toast } from "@/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mi Proyecto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased font-body`} suppressHydrationWarning>
        <Header />
        <NavigationMenu />
        <main className="w-full mt-30 bg-background">{children}</main>
        <Footer />
        <Toast />
      </body>
    </html>
  );
}
